### PR TITLE
High preset NVS storage + fix for storing first low preset

### LINKED ISSUE #1: Low preset height needs to be set first
It is issue in the code, low preset height needs to be set first after boot, buttons would probably react wrongly after double click. Double click up would go to low preset and vice versa, not tested. Fix is simple.

### PR DESCRIPTION
**Pull request by peterdragun**
Closes #1

I was also thinking about adding an option for restoring the NVS to 0, but not sure if we would ever need that? What do you think?

### CODE REVIEW

File: main/main.c [hunk 1]
```diff
@@ -40,12 +47,91 @@ static volatile uint8_t go_to_height = 0;
...
     if (low_height == 0) {
+        // store the new height as the low height first if both haven't been set yet
         low_height = height;
     } else if (high_height == 0) {
-        high_height = height;
+        // low was already set, we need to make sure that the new height is higher than the low height
+        if (height > low_height) {
+            high_height = height;
+        } else {
+            high_height = low_height;
```
[the remark this answers is not in the document]
Comment (peterdragun) [reply main/main.c:122]: 0 is never a valid value.

File: main/main.c [hunk 2]
```diff
@@ -25,27 +27,111 @@
...
+static esp_err_t nvs_save_preset_heights(void)
+{
+    nvs_handle_t nvs_handle;
+    esp_err_t err;
+
+    err = nvs_open(NVS_NAMESPACE, NVS_READWRITE, &nvs_handle);
+    if (err != ESP_OK) {
+        ESP_LOGE(TAG, "Error opening NVS handle: %s", esp_err_to_name(err));
+        return err;
+    }
```
Comment (Dzarda7) [inline main/main.c]:
```suggestion
    RETURN_ON_ERROR(nvs_open(NVS_NAMESPACE, NVS_READWRITE, &nvs_handle));
```

I think this would be nice, then print the final error message from the function.

File: main/main.c [hunk 3]
```diff
@@ -221,6 +328,12 @@ void app_main(void)
         ESP_LOGI(TAG, "Main loop: go_to_height_active=%s, height=%u, go_to_height=%u, low_height=%u, high_height=%u",
                  go_to_height_active ? "true" : "false", height, go_to_height, low_height, high_height);
 
+        // Log preset heights status every 10 seconds (100 iterations * 100ms)
+        static uint32_t loop_counter = 0;
+        if (++loop_counter % 100 == 0) {
+            ESP_LOGI(TAG, "Preset heights status - Low: %u cm, High: %u cm", low_height, high_height);
+        }
+
```
Comment (Dzarda7) [inline main/main.c]: As Linus said "this makes the world actively a worse place to live".

File: main/main.c (hunk 2 above)
Comment (peterdragun) [reply main/main.c]: That will only work for this case, in other cases I also need to close the nvs. But sure I can create my own macro if you prefer it this way

File: main/main.c (hunk 3 above)
Comment (peterdragun) [reply main/main.c]: Not really, at least you see what the current preset is for debugging, and it does not flood the serial. If you have a better idea how to implement this, I am all ears :) You know, be constructive 🙃  otherwise your comment does not really help and "makes the world actively a worse place to live"

File: main/main.c (hunk 2 above)
Comment (Dzarda7) [reply main/main.c]: Okay, we can keep this.

File: main/main.c (hunk 3 above)
Comment (Dzarda7) [reply main/main.c]: We can keep this if you remove the kconfig option to set loop delay, that is so wrong that I am able to overlook this. Setting the loop delay to something not even that that big like 2 seconds can cause endless trial of table movement.

Comment (Dzarda7) [reply main/main.c]: Okay, you have a limit to 1s, but still. Also initial movement time remove.

Comment (peterdragun) [reply main/main.c]: Removed, it will be printed when the chip is started, again when storing the value, and then again when moving to the position. This was never logged before, so I guess we don't really need it. If you want to debug this, you can add it anyway.

File: main/main.c (hunk 2 above)
Comment (peterdragun) [reply main/main.c]: Updated to use the proposed macro at least in cases where it makes sense.

**Comment by Dzarda7** [comment]
> I was also thinking about adding an option for restoring the NVS to 0, but not sure if we would ever need that? What do you think?

I think we do not need it, it is ok to just erase flash.

**Comment by Dzarda7** [comment]
LGTM, thanks.
